import React from "react";
import { AlertTriangle, Info, CheckCircle2 } from "lucide-react";

/**
 * Insights
 * --------
 * Short, actionable insights generated by *rule-based* logic.
 *
 * IMPORTANT (architecture):
 *   The component is intentionally split so the insight *generator*
 *   (`generateInsights`) is a pure function over { apps, weeklyHistory }.
 *
 *   In the future, this generator can be swapped out for an
 *   OpenAI-powered service that returns the same shape:
 *     [{ id, severity: "warn"|"info"|"good", text }]
 *
 *   The view layer below stays the same.
 *
 * Future (not implemented):
 *   - Detect behavioral patterns over time
 *   - Provide coaching insights
 *   - Identify trends and anomalies
 *   - Personalize recommendations
 */

export default function Insights({ apps, weeklyHistory }) {
  const insights = generateInsights({ apps, weeklyHistory }).slice(0, 3);

  return (
    <div className="card">
      <h3 className="section-title" style={{ marginTop: 0 }}>Insights</h3>

      <div className="insights-list">
        {insights.length === 0 && (
          <div className="insight good">
            <span className="icon"><CheckCircle2 size={16} /></span>
            <span className="text">Nothing to flag — you're tracking well today.</span>
          </div>
        )}

        {insights.map((ins) => (
          <div key={ins.id} className={`insight ${ins.severity}`}>
            <span className="icon">
              {ins.severity === "warn" && <AlertTriangle size={16} />}
              {ins.severity === "info" && <Info size={16} />}
              {ins.severity === "good" && <CheckCircle2 size={16} />}
            </span>
            <span className="text" dangerouslySetInnerHTML={{ __html: ins.text }} />
          </div>
        ))}
      </div>
    </div>
  );
}

/* =============================================================
   Pluggable insight generator (rule-based today, AI later).
   Pure function. Swap-in target for the future OpenAI version.
   ============================================================= */
export function generateInsights({ apps, weeklyHistory }) {
  const out = [];
  const active = apps.filter((a) => a.status !== "coming_soon");

  // Per-app: not started yet
  active.forEach((app) => {
    if (app.todayXP === 0 && app.dailyGoal > 0) {
      out.push({
        id: `not-started-${app.id}`,
        severity: "warn",
        text: `You haven't worked on <strong>${app.name}</strong> today.`
      });
    }
  });

  // Per-app: behind by >=40%
  active.forEach((app) => {
    if (app.dailyGoal === 0 || app.todayXP === 0) return;
    const pctDone = app.todayXP / app.dailyGoal;
    if (pctDone < 1) {
      const pctBehind = Math.round((1 - pctDone) * 100);
      if (pctBehind >= 40) {
        out.push({
          id: `behind-${app.id}`,
          severity: "info",
          text: `You're <strong>${pctBehind}%</strong> behind your <strong>${app.name}</strong> goal.`
        });
      }
    }
  });

  // "One left to finish all goals"
  const incomplete = active.filter((a) => a.todayXP < a.dailyGoal);
  if (incomplete.length === 1) {
    const last = incomplete[0];
    out.push({
      id: `one-left-${last.id}`,
      severity: "info",
      text: `Complete <strong>${last.name}</strong> to finish all of today's goals.`
    });
  }

  // All complete -> celebrate
  if (incomplete.length === 0) {
    out.push({
      id: "all-complete",
      severity: "good",
      text: "All daily goals complete. Strong day."
    });
  }

  // Weekly trend: today < average of prior 6
  if (weeklyHistory && weeklyHistory.length >= 2) {
    const today = weeklyHistory[weeklyHistory.length - 1];
    const prior = weeklyHistory.slice(0, -1);
    const avg =
      prior.reduce((s, d) => s + d.xp, 0) / Math.max(prior.length, 1);
    if (avg > 0 && today.xp < avg * 0.6) {
      out.push({
        id: "below-weekly-avg",
        severity: "warn",
        text: `Today's XP is below your weekly average. A short session can pull you back on track.`
      });
    }
  }

  // Sort: warn -> info -> good
  const order = { warn: 0, info: 1, good: 2 };
  out.sort((a, b) => order[a.severity] - order[b.severity]);

  return out;
}
