-- ================================================================
-- VPA Learning OS — Passwordless student auth (M16-L1)
--
-- K-2 students don't have email addresses or passwords. Login is:
--   1. Class code (5-char alphanumeric, printed on a roster sheet)
--   2. Tap your name + avatar in the class roster
--   3. Type a 4-digit PIN
--
-- This migration extends the existing `students` and `teacher_classes`
-- tables with the columns needed for that flow, and creates a new
-- `student_sessions` table to track active student sessions
-- (replaces Supabase Auth for kid accounts; teachers still use
-- Supabase Auth for email/password / Google).
--
-- Design rules (mirrors 0004_teacher_roster.sql):
--   1. Service-role mints session tokens. SPA never sees pin_hash.
--   2. Existing teacher RLS policies remain unchanged.
--   3. Student session bearer is validated by the API layer, not
--      Postgres RLS — sessions live above the auth.uid() boundary.
--   4. PII stays minimal: first_name + last_initial + grade only.
--      No DOB, no last name, no email on the student row itself.
--   5. COPPA-aware: parent_email is OPTIONAL and used only for
--      consent + reports, never for student login.
--
-- Idempotent. Safe to re-run.
-- ================================================================

-- ---- students: passwordless-login columns ------------------------
-- The base `students` table is created upstream by the VPA OS.
-- We add the columns we need without changing existing semantics.
-- auth_user_id stays nullable so a passwordless-login student never
-- needs a Supabase Auth row.

alter table public.students
  add column if not exists first_name             text,
  add column if not exists last_initial           text,
  add column if not exists grade                  text,
  add column if not exists avatar_emoji           text,
  add column if not exists pin_hash               text,
  add column if not exists pin_salt               text,
  add column if not exists qr_login_token_hash    text,
  add column if not exists is_active              boolean not null default true,
  add column if not exists parent_email           text,
  add column if not exists created_by_teacher     uuid references auth.users(id) on delete set null,
  add column if not exists last_login_at          timestamptz;

-- Sanity check on PIN length (we hash a 4-digit string; the column
-- holds the hash, not the digits).
-- last_initial defensive constraint: single character.
do $$
begin
  if not exists (
    select 1 from information_schema.constraint_column_usage
    where table_name = 'students' and constraint_name = 'students_last_initial_chk'
  ) then
    alter table public.students
      add constraint students_last_initial_chk
      check (last_initial is null or length(last_initial) <= 2);
  end if;
end $$;

-- ---- teacher_classes: class code ---------------------------------
-- 5-char uppercase alphanumeric (no I/O/0/1 — too ambiguous in
-- print). Generated server-side; unique across the table.

alter table public.teacher_classes
  add column if not exists class_code text;

create unique index if not exists tc_class_code_uniq
  on public.teacher_classes (class_code)
  where class_code is not null;

-- ---- student_sessions ------------------------------------------
-- One row per active passwordless student session. The token is
-- generated by the API layer (random 256-bit), only the hash is
-- stored. Sessions expire after 30 days (re-login required) or when
-- a teacher revokes them.

create table if not exists public.student_sessions (
  id              uuid primary key default gen_random_uuid(),
  student_id      uuid not null references public.students(id) on delete cascade,
  token_hash      text not null unique,
  device_label    text,
  expires_at      timestamptz not null default (now() + interval '30 days'),
  revoked_at      timestamptz,
  created_at      timestamptz not null default now(),
  last_seen_at    timestamptz not null default now()
);

create index if not exists ss_student_idx
  on public.student_sessions (student_id);
create index if not exists ss_active_idx
  on public.student_sessions (token_hash)
  where revoked_at is null;

-- ================================================================
-- RLS for student_sessions
-- ================================================================
-- Validation always runs through the API (service role). Teachers
-- can READ their roster's sessions (e.g. "this student logged in 5
-- minutes ago"); they can REVOKE sessions for their roster too.
-- Students never touch this table directly via the SPA.

alter table public.student_sessions enable row level security;

drop policy if exists ss_teacher_select on public.student_sessions;
drop policy if exists ss_teacher_revoke on public.student_sessions;

create policy ss_teacher_select
  on public.student_sessions for select
  using (public.teacher_can_see_student(student_id));

create policy ss_teacher_revoke
  on public.student_sessions for update
  using (public.teacher_can_see_student(student_id))
  with check (public.teacher_can_see_student(student_id));

-- ================================================================
-- Helper: claim a class code → return class_id (service-role only).
-- Used by /api/student-roster-by-code so the SPA can fetch the
-- avatar grid for the student to pick from.
-- ================================================================

create or replace function public.class_id_from_code(p_code text)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.teacher_classes
  where class_code = upper(p_code)
    and archived = false
  limit 1;
$$;

-- ================================================================
-- Done. M16-L1 schema landed.
-- ================================================================
